### ISSUE TITLE
Minor feature - "done checkboxes"

### ISSUE THREAD

**Issue by ddevz** [TheXXOs/ithkapp#15]
A possible minor feature would be to have a checkbox on each answer.  (I.E. one for plexity, one for similarity, one for connectedness, etc.)  The checkbox would merely be a way to let your future self know that you have gone through all the options for this answer and think you have gotten it right.

I.E. anything without a checked checkbox would still be on your "todo" list while creating the word.

**Comment by TheXXOs** [comment]
Done in commit [84eaebe](https://github.com/TheXXOs/ithkapp/commit/84eaebeb79cc6836ddf8beea02a6941361b2f41b)! The status of the done checkboxes is saved upon switching words (each word has its unique box states) and upon saving/loading a .json file. They are hidden by default, but can be turned on in settings.

**Comment by ddevz** [comment]
Thanks!
