### ISSUE TITLE
Sentence menu is very broken

### ISSUE THREAD

**Issue by TheXXOs** [TheXXOs/ithkapp#17]
When attempting to change words in the sentence menu, it will often replace the word you want to change to with either an empty word or the word that was just selected - I may need to rewrite the word switching code.

**Comment by Colonizor48** [comment]
Yes Please do this

**Comment by TheXXOs** [comment]
Never mind, it's still a problem.

**Comment by TheXXOs** [comment]
Update: It was only an issue in the testing versions of Ithkapp.
