### ISSUE TITLE
T3 Affix interpreted as Referential Shortcut when with T4 Affix(es) together in the same Slot...?

### ISSUE THREAD

**Issue by ryanlo713** [TheXXOs/ithkapp#20]
![image](https://github.com/TheXXOs/ithkapp/assets/12672523/29310598-61fa-4ba4-bfa1-aece1882e0ff)
![image](https://github.com/TheXXOs/ithkapp/assets/12672523/da1161d8-1dca-4839-90cf-05b3f9102eeb)

**Comment by TheXXOs** [comment]
should be fixed! the website will hopefully be updated soon
